---
- name: remove old golang
  file:
    path: /usr/local/go
    state: absent
  become: true

- name: download golang
  get_url:
    url: https://dl.google.com/go/go1.11.linux-amd64.tar.gz
    dest: /tmp/go.tar.gz
    force: yes
    checksum: "sha256:b3fcf280ff86558e0559e185b601c9eade0fd24c900b4c63cd14d1d38613e499"

- name: install golang
  unarchive:
    src: /tmp/go.tar.gz
    dest: /usr/local
  become: true

- name: remove golang download
  file:
    path: /tmp/go.tar.gz
    state: absent

- name: bin dir present
  file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: get golang dep
  get_url:
    url: https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
    dest: "{{ ansible_env.HOME }}/bin/dep"
    force: yes
    checksum: "sha256:31144e465e52ffbc0035248a10ddea61a09bf28b00784fd3fdd9882c8cbb2315"
