---
- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  gather_facts: true

  roles:
  - {role: dot, tags: [dot, bash]}
  - {role: ssh, tags: [ssh]}
  - {role: packages, tags: [packages]}
  - {role: sudoers, tags: [sudo]}
  - {role: docker, tags: [docker]}
  - {role: vscode, tags: [vscode]}
  - {role: limits, tags: [limits]}
  - {role: chrome, tags: [chrome]}
  - role: newrelic-infra
    tags: [newrelic-infra]
    vars:
      license_key: "{{ nri_license_key }}"
