---
- name: a playbook to setup my local machine with my basic customizations
  hosts: local
  connection: local
  gather_facts: false

  pre_tasks:
    - name: Update and upgrade apt packages
      become: true
      apt:
        upgrade: yes
        update_cache: yes
        force_apt_get: yes
      tags:
        - apt
    - name: Run apt-get autoremove
      become: true
      apt:
        autoremove: yes
        force_apt_get: yes
      tags:
        - apt
    - name: Run apt-get autoremove
      become: true
      shell: /usr/sbin/update-ca-certificates
      tags:
        - apt

  tasks:
    - name: install dependencies
      apt:
        name: "{{ item }}"
        state: latest
        force_apt_get: yes
        install_recommends: no
      with_items:
        - vim 
        - htop
        - curl
        - wget
        - automake
        - make
        - m4
        - libtool
        - pkg-config
        - libevent-dev
        - libncurses-dev
        - tree
        - git
        - sshpass
        - snapcraft
        - rpm
        - jq
        - build-essential
        - keychain
        - unzip
        - ack-grep
        - direnv
        - p7zip-full
        - p7zip-rar
        - python3-venv
        - mingw-w64
      become: true
      tags:
        - apt
    - name: Install httpie
      pip:
        name: httpie
        state: latest
      tags:
        - pip
    - name: Install awscli
      pip:
        name: awscli
        state: latest
        extra_args: --user
      tags:
        - pip
    - name: Install virtualenv
      pip:
        name: virtualenv
        state: latest
      tags:
        - pip
    - name: Install pipenv
      pip:
        name: pipenv
        state: latest
      tags:
        - pip
    - name: Install CloudFormation Linter
      pip:
        name: cfn-lint
        state: latest
        extra_args: --user
      tags:
        - pip
    - name: Install AWS SAM CLI
      pip:
        name: aws-sam-cli
        state: latest
        extra_args: --user
      tags:
        - pip

  roles:
   - { role: dot, tags: [dot, bash] }
   - { role: ssh, tags: [ssh] }
   - { role: andrewrothstein.sudoers, tags: [sudo] }
   - { role: golang, tags: [golang] }
   - { role: k8s, tags: [k8s] }
   - { role: wsl, tags: [wsl] }

  post_tasks:
    - shell: echo 'I":" Beginning to configure web server..'
