---
- name: A playbook to setup my local machine with my basic customizations
  hosts: localhost
  gather_facts: false

  pre_tasks:
    - name: Collect system facts
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - '!min'
          - date_time
          - distribution
          - env
          - lsb  # Linux Standard Base (LSB)
          - os_family  # Distribution
          - system  # Architecture
          - user
      tags:
        - always
    - name: Load Linux vars
      ansible.builtin.include_vars: linux.yml
      when: ansible_system == 'Linux'
      tags:
        - always
    - name: Load OSX vars
      ansible.builtin.include_vars: osx.yml
      when: ansible_system == 'Darwin'
      tags:
        - always
    - name: Debug
      ansible.builtin.debug:
        msg: "pre_task ssh.id_rsa.pub {{ ssh.id_rsa.pub }}"
      tags:
        - always

  roles:
    - {role: debug, tags: [debug]}
    - {role: dot, tags: [dot, bash]}
    - {role: ssh, tags: [ssh]}
    - {role: wsl, tags: [wsl]}
    - {role: osx, tags: [osx]}
    - {role: packages, tags: [packages]}
    - {role: gui, tags: [gui]}
    - {role: sudoers, tags: [sudo]}
    - {role: docker, tags: [docker]}
    - {role: vscode, tags: [vscode]}
    - {role: limits, tags: [limits]}
    - {role: chrome, tags: [chrome]}
    - {role: golang, tags: [golang]}
    - {role: rust, tags: [rust]}
    - role: newrelic-infra
      tags: [newrelic-infra]
      vars:
        license_key: "{{ nri_license_key }}"
    - {role: nvidia-cuda, tags: [nvidia-cuda]}
