---
- name: Setup newrelic-infra config file
  become: true
  become_user: root
  ansible.builtin.template:
    src: etc/newrelic-infra.yml.j2
    dest: /etc/newrelic-infra.yml
    mode: 0440

- name: Install New Relic Infrastructure agent
  become: true
  ansible.builtin.package:
    name:
      - newrelic-infra
    state: latest

- name: Reload New Relic Infrastructure agent
  become: true
  ansible.builtin.service:
    name: newrelic-infra
    enabled: true
    state: restarted
