---
- name: debug check
  debug:
    msg:
      - "ansible_distribution {{ ansible_distribution }}"
      - "major version {{ ansible_distribution_major_version }}"
      - "version {{ ansible_distribution_version }}"

- name: clean up Ubuntu and Debian
  become: true
  apt:
    autoremove: true
    force_apt_get: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
