---
- name: Install generic packages
  package:
    name:
      - ack-grep
      - automake
      - ca-certificates
      - curl
      - direnv
      - dos2unix
      - git
      - gnupg2
      - htop
      - ipcalc
      - iperf3
      - jq
      - keychain
      - libbz2-dev
      - libevent-dev
      - libncurses-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - libtool
      - m4
      - make
      - mingw-w64
      - p7zip-full
      - p7zip-rar
      - pass
      - sshfs
      - sshpass
      - sudo
      - tmux
      - traceroute
      - tree
      - unzip
      - vim
      - wget
      - zlib1g-dev
    state: latest
  become: true

- name: Install ubuntu packages
  package:
    name:
      - apt-transport-https
      - build-essential
      - pkg-config
      - rpm
      - software-properties-common
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
