---
- name: stat ADR
  ansible.builtin.stat:
    path: "{{ lookup('env','HOME') }}/bin/adr-tools"
  register: adr_stat

- name: Get ADR Tools
  ansible.builtin.unarchive:
    src: https://github.com/npryce/adr-tools/archive/3.0.0.zip
    dest: /tmp
    remote_src: true
  when: adr_stat.stat.exists == False

- name: Copy ADR Tools
  ansible.builtin.command: "mv  /tmp/adr-tools-3.0.0  {{ lookup('env','HOME') }}/bin/adr-tools"
  when: adr_stat.stat.exists == False
