---
- name: Install generic packages
  package:
    name:
      - vim
      - htop
      - curl
      - wget
      - automake
      - make
      - m4
      - libtool
      - pkg-config
      - libevent-dev
      - libncurses-dev
      - tree
      - git
      - sshpass
      - snapcraft
      - rpm
      - jq
      - keychain
      - unzip
      - ack-grep
      - direnv
      - p7zip-full
      - p7zip-rar
      - mingw-w64
      - pass
      - gnupg2
      - traceroute
      - zlib1g-dev
      - libssl-dev
      - libreadline-dev
      - libbz2-dev
      - libsqlite3-dev
      - ipcalc
      - dos2unix
      - python3-venv
      - sudo
      - ca-certificates
      - tmux
    state: latest
  become: true

- name: Install ubuntu packages
  package:
    name:
      - rpm
      - apt-transport-https
      - software-properties-common
      - build-essential
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
