---
- name: Create ADR Tools dir
  file:
    path: "/tmp/adr-tools"
    state: directory
  tags:
    - packages

- name: Get ADR Tools
  unarchive:
    src: https://github.com/npryce/adr-tools/archive/3.0.0.zip
    dest: "/tmp/adr-tools"
    remote_src: true
  tags:
    - packages

- name: Install ADR Tools
  command: cp -R /tmp/adr-tools/adr-tools-3.0.0 "{{ lookup('env','HOME') }}/bin/adr-tools"
  tags:
    - packages

- name: Clean ADR Tools dir
  file:
    path: "/tmp/adr-tools"
    state: absent
  tags:
    - packages
