---
- name: Install global Python packages
  ansible.builtin.pip:
    name:
      - httpie
      - wheel
      - yamllint
    virtualenv: "{{ lookup('env','HOME') }}/venv"
    # Fix for creating the virtual env
    virtualenv_command: /usr/bin/python3 -m venv 
    state: latest
