---
- name: Only run "update_cache=yes" when last one is more than 3600 seconds ago
  become: true
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install Debian generic packages
  ansible.builtin.package:
    name:
      - ack-grep
      - bind9-dnsutils
      - libpq-dev
      - libbz2-dev
      - libevent-dev
      - libncurses-dev
      - libsqlite3-dev
      - libssl-dev
      - zlib1g-dev
      - libreadline-dev
      - mingw-w64
      - p7zip-full
      - p7zip-rar
      - pkg-config
  when: ansible_os_family == 'Debian'

- name: Install generic packages
  ansible.builtin.package:
    name:
      - automake
      - ca-certificates
      - cmake
      - curl
      - direnv
      - dos2unix
      - dpkg-dev
      - g++
      - gcc
      - git
      - gnupg2
      - htop
      - ipcalc
      - iperf3
      - jq
      - keychain
      - libtool
      - m4
      - make
      - pass
      - sshfs
      - sshpass
      - sudo
      - tmux
      - traceroute
      - tree
      - unzip
      - vim
      - wget
    state: latest
  become: true

- name: Install ubuntu packages
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - build-essential
      - pkg-config
      - rpm
      - software-properties-common
    state: latest
    install_recommends: false
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Install additonal pico toolchain packages
  ansible.builtin.apt:
    name:
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi
      - libstdc++-arm-none-eabi-newlib
    state: latest
    install_recommends: false
  become: true
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
