# Managed by Ansible dot role
export PATH="$HOME/.local/bin:$PATH"

# last status
alias last-status="echo $?"

# fix clock skew
alias clock-fix="sudo hwclock -s"

# git status
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")\$ '

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_HIDE_IF_PWD_IGNORED=true
export GIT_PS1_SHOWCOLORHINTS=true

# Attach or create a new tmux session
alias tmux-new-session='tmux new-session -A -s'

# Load direnv
eval "$(direnv hook bash)"
