---

- name: Remove old vscode.list
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/vscode.list
    state: absent

- name: Add VSCode APT repo
  become: true
  ansible.builtin.deb822_repository:
    name: vscode
    uris: https://packages.microsoft.com/repos/vscode
    types: deb
    components: main
    suites: stable
    architectures: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    signed_by: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  register: vscode_repo
  when: ansible_distribution == 'Ubuntu'

- name: Only run "update_cache=yes" when VSCode APT repo updated
  become: true
  ansible.builtin.apt:
    update_cache: true
  when:
    - ansible_distribution == 'Ubuntu'
    - vscode_repo.changed

- name: Install Visual Studio Code
  become: true
  ansible.builtin.package:
    name: code
    state: latest
