---
- name: Add MSFT APT key
  become: true
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Add APT repo
  become: true
  apt_repository:
    repo: 'deb [arch=amd64]
      https://packages.microsoft.com/repos/vscode
      stable
      main'
    state: present
    filename: vscode
  when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Debian'

- name: Install Visual Studio Code
  become: true
  package:
    name: code
    state: latest
