# Managed by Ansible dot role

export PATH=/usr/local/go/bin:$PATH

# Alias Widnows Docker executable to Linux Docker
alias docker="docker.exe"
# Used for Makefiles
export DOCKER="docker.exe"

# last status
alias last-status="echo $?"

