# Managed by Ansible dot role

export PATH=/usr/local/go/bin:$PATH

# Alias Widnows Docker executable to Linux Docker
alias docker="docker.exe"
alias docker-compose="docker-compose.exe"
# Used for Makefiles
export DOCKER="docker.exe"
export DOCKER_COMPOSE="docker-compose.exe"

# last status
alias last-status="echo $?"

# git status
PS1='${debian_chroot:+($debian_chroot)}\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$(__git_ps1 " (%s)")\$ '

export GIT_PS1_SHOWDIRTYSTATE=true
export GIT_PS1_SHOWSTASHSTATE=true
export GIT_PS1_SHOWUNTRACKEDFILES=true
export GIT_PS1_SHOWUPSTREAM="auto"
export GIT_PS1_HIDE_IF_PWD_IGNORED=true
export GIT_PS1_SHOWCOLORHINTS=true

# Load direnv
eval "$(direnv hook bash)"
