---
# Sets up the prviate and public ssh keys

- name: Create .ssh dir
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.ssh"
    state: directory
    mode: 0700

- name: Copy id_rsa file
  ansible.builtin.copy:
    content: "{{ ssh.id_rsa.prvt }}"
    dest: "{{ lookup('env','HOME') }}/.ssh/id_rsa"
    mode: 0600

- name: Create id_rsa.pub file
  ansible.builtin.copy:
    content: "{{ ssh.id_rsa.pub }}"
    dest: "{{ lookup('env','HOME') }}/.ssh/id_rsa.pub"
    mode: 0600
