---

- name: Remove old chrome.list
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/chrome.list
    state: absent

- name: Remove default Ubuntu Chrome
  become: true
  ansible.builtin.file:
    path: /etc/apt/sources.list.d/google-chrome.list
    state: absent

- name: Add Chrome APT repo
  become: true
  ansible.builtin.deb822_repository:
    name: chrome
    uris: http://dl.google.com/linux/chrome/deb/
    types: deb
    components: main
    suites: stable
    architectures: "{{ 'arm64' if ansible_architecture == 'aarch64' else 'amd64' }}"
    signed_by: https://dl-ssl.google.com/linux/linux_signing_key.pub
    state: present
  register: chrome_repo
  when: ansible_distribution == 'Ubuntu'

- name: Only run "update_cache=yes" when Chrome APT repo updated
  become: true
  ansible.builtin.apt:
    update_cache: true
  when:
    - ansible_distribution == 'Ubuntu'
    - chrome_repo.changed
