---
- name: copy gitconfig
  copy:
    src: gitconfig
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    force: true

- name: copy tmux.conf
  copy:
    src: tmux.conf
    dest: "{{ ansible_env.HOME }}/.tmux.conf"
    force: true

- name: copy bash_aliases
  copy:
    src: bash_aliases
    dest: "{{ ansible_env.HOME }}/.bash_aliases"
    force: true

- name: copy profile.d/10-keychain.sh
  copy:
    src: etc/profile.d/10-keychain.sh
    dest: /etc/profile.d/10-keychain.sh
    mode: 0644
    force: true
  become: true
