---
- name: Create /etc/wsl.conf
  ansible.builtin.template:
    src: etc/wsl.conf.j2
    dest: /etc/wsl.conf
  become: true
  become_user: root

- name: Run systemd-timesyncd tasks
  ansible.builtin.include_tasks: systemd-timesyncd.yml
