---
# docker-ce docker-ce-cli containerd.io
- name: Install Docker
  become: true
  package:
    name:
      - binfmt-support
      - docker-ce
      - docker-ce-cli
      - docker-compose-plugin
      - containerd.io
      - qemu-user-static
      - skopeo
    state: latest

- name: Add user to Docker
  become: true
  user:
    name: '{{ current_username }}'
    append: true
    groups:
      - docker

- name: Start Docker
  become: true
  service:
    name: docker
    enabled: true
    state: reloaded
