---
- name: Add Docker Ubuntu APT key
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_distribution == 'Ubuntu'

- name: Add Docker Ubuntu repo
  become: true
  ansible.builtin.apt_repository:
    repo: 'deb [arch=amd64]
      https://download.docker.com/linux/ubuntu
      {{ ansible_lsb.codename }}
      stable'
    state: present
    filename: docker
  when: ansible_distribution == 'Ubuntu'
