---
- name: Install useful command tools
  community.general.homebrew:
    name:
      - automake
      - make
      - cmake
      - m4
      - ack
      - htop
      - jq
      - curl
      - wget
      - git
      - dos2unix
      - tree
      - direnv
      - pass
      - gnupg
      - keychain
      - tmux
      - zsh-completions
      - rustup-init
      - k9s
      - nvm
      - graphviz
      - rbenv
      - telnet
    state: upgraded

- name: Install useful apps
  community.general.homebrew_cask:
    name:
      - firefox
      - iterm2
      # - google-chrome
      - visual-studio-code
      - jetbrains-toolbox
    state: present

- name: Create NVM directory
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.nvm"
    state: directory
    recurse: true
    owner: "{{ ansible_user_id }}"
    group: staff
