---
- name: Install useful command tools
  community.general.homebrew:
    name:
      - automake
      - make
      - m4
      - ack
      - htop
      - jq
      - curl
      - wget
      - git
      - dos2unix
      - tree
      - direnv
      - pass
      - gnupg
      - keychain
      - tmux
      - zsh-completions
      - rustup-init
      - k9s
      - nvm
      - graphviz
      - libpq
      - rbenv
      - telnet
    state: present

- name: Install useful apps
  community.general.homebrew_cask:
    name:
      - firefox
      - google-chrome
      - visual-studio-code
      - slack
      - jetbrains-toolbox
      - zoom
      - docker
      - google-cloud-sdk
      - microsoft-edge
      - microsoft-teams
    state: present

- name: Create NVM directory
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.nvm"
    state: directory
    recurse: true
    owner: croman
    group: staff
