---
- name: Install useful command tools
  community.general.homebrew:
    name:
      - ack
      - automake
      - bash
      - cmake
      - coreutils
      - curl
      - direnv
      - dos2unix
      - gcc
      - git
      - gnupg
      - gpg2
      - graphviz
      - htop
      - jq
      - keychain
      - m4
      - make
      - nvm
      - pass
      - pinentry
      - pyenv
      - rbenv
      - telnet
      - tmux
      - tree
      - wget
      - zsh-completions
      - ykman
    state: upgraded

- name: Install k8s tools
  community.general.homebrew:
    name:
      - helm
      - k9s
      - kubectx
      - kubernetes-cli
      - vault
    state: upgraded

- name: Install useful apps
  community.general.homebrew_cask:
    name:
      - firefox
      - iterm2
      - jetbrains-toolbox
      - visual-studio-code
    state: present

- name: Create NVM directory
  ansible.builtin.file:
    path: "{{ lookup('env','HOME') }}/.nvm"
    state: directory
    recurse: true
    owner: "{{ ansible_user_id }}"
    group: staff
